- name: 安装ceph-deploy
  become: true
  yum: name=ceph-deploy state=latest

- name: 替换配置文件
  become: true
  template: src=ceph.conf.j2 dest=/etc/ceph/ceph.conf

- name: 创建目录
  file:
    path: "{{item}}"
    state: directory
  with_items:
  - "{{ceph_deploy_dir}}"


- name: change the user root password
  shell: 'cd /etc/ceph && ceph-deploy new ceph-node-1'